project_id = "rbsuobpaqwtmiesxwcaw"

[functions]
[functions.analyze-lead]
[functions.create-checkout]
[functions.generate-leads-with-ai]
[functions.search-company]
[functions.send-automated-emails]
[functions.stripe-webhook]