project_id = "rbsuobpaqwtmiesxwcaw"

[[functions]]
name = "create-checkout"
verify_jwt = true

[[functions]]
name = "generate-leads-with-ai"
verify_jwt = true

[[functions]]
name = "send-automated-emails"
verify_jwt = true

[[functions]]
name = "stripe-webhook"
verify_jwt = false

[[functions]]
name = "analyze-lead"
verify_jwt = true