export const plans = [
  {
    name: "Gratuit",
    description: "Pour tester notre solution",
    price: "0€",
    features: [
      "3 leads par jour",
      "Score de qualification",
      "Analyse IA basique",
      "Export CSV",
    ],
    buttonText: "Commencer gratuitement",
    type: "free",
  },
  {
    name: "Pro",
    description: "Pour les professionnels qui veulent plus",
    price: "14,99€",
    features: [
      "250 leads par mois",
      "Analyse IA avancée",
      "Export multi-formats",
      "Accès API",
      "Support prioritaire",
    ],
    buttonText: "Commencer l'essai gratuit",
    type: "pro",
    popular: true,
    priceId: "price_1OqKHyKez0igoNdCnewVaA8M",
  },
  {
    name: "Entreprise",
    description: "Pour les grandes équipes",
    price: "Sur mesure",
    features: [
      "Leads illimités",
      "Analyse IA personnalisée",
      "API dédiée",
      "Account manager dédié",
      "Formation personnalisée",
    ],
    buttonText: "Contacter l'équipe commerciale",
    type: "enterprise",
  },
];