export const plans = [
  {
    name: "Gratuit",
    description: "Testez notre solution sans engagement",
    price: "0€",
    features: [
      "3 leads offerts",
      "Analyse IA avancée",
      "Multi format",
      "Support prioritaire",
      "Idéal pour découvrir sans risque",
      "Accès basique aux automatisations (Bientôt)",
      "1 workflow d'automatisation (Bientôt)",
    ],
    buttonText: "Commencer gratuitement",
    type: "free",
  },
  {
    name: "Pro",
    description: "Idéal pour les petites entreprises",
    price: "24,99€",
    features: [
      "200 leads garantis par mois",
      "10 leads par jour maximum",
      "Analyse IA avancée",
      "Export multi-formats",
      "Accès API",
      "Support prioritaire",
      "0,125 €/lead",
      "Automatisations avancées (Bientôt)",
      "3 workflows d'automatisation (Bientôt)",
      "Intégration OpenAI (Bientôt)",
      "Webhooks personnalisés (Bientôt)",
    ],
    buttonText: "Commencer",
    type: "pro",
    popular: true,
    priceId: "price_1OqKHyKez0igoNdCnewVaA8M",
  },
  {
    name: "Premium",
    description: "Pour tester à plus grande échelle",
    price: "59,99€",
    features: [
      "500 leads garantis par mois",
      "20 leads par jour maximum",
      "Analyse IA avancée et personnalisée",
      "Export multi-formats",
      "API dédiée pour automatisation",
      "Support prioritaire expert",
      "0,12 €/lead",
      "Automatisations illimitées (Bientôt)",
      "Workflows illimités (Bientôt)",
      "Intégration OpenAI avancée (Bientôt)",
      "Webhooks & API personnalisés (Bientôt)",
      "Enrichissement des leads automatique (Bientôt)",
    ],
    buttonText: "Commencer",
    type: "enterprise",
  },
];