export const plans = [
  {
    name: "Freemium",
    description: "Parfait pour débuter avec LeadGen Pro",
    price: "0€",
    features: [
      "3 leads par jour",
      "90 leads par mois",
      "Analyse IA basique",
      "Export PDF",
      "Support par email",
    ],
    buttonText: "Commencer gratuitement",
    type: "free",
  },
  {
    name: "Pro",
    description: "En seulement 3 minutes, accédez aux meilleurs leads du marché. Nos leads sont minutieusement qualifiés et analysés par notre IA spécialisée, vous donnant accès à toutes les informations essentielles pour proposer des services parfaitement alignés avec leurs besoins d'amélioration.",
    price: "14,99€",
    features: [
      "250 leads par mois",
      "Analyse IA avancée",
      "Export multi-formats",
      "Support prioritaire",
      "API Access",
    ],
    buttonText: "Choisir Pro",
    type: "pro",
    popular: true,
    priceId: "price_1QV8EyB0B6nBBCbUWZIuAQ8q",
  },
  {
    name: "Enterprise",
    description: "Solution complète pour les grandes équipes",
    price: "199€",
    features: [
      "Génération illimitée",
      "Analyse IA personnalisée",
      "Tous les formats d'export",
      "Support dédié 24/7",
      "API illimitée",
      "Intégrations sur mesure",
    ],
    buttonText: "Contacter les ventes",
    type: "enterprise",
    priceId: "price_1QV8FaB0B6nBBCbUFoQrwDwm",
  },
];